name: Python CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: initialization
      run: make install

    - name: linter check
      run: make lint
